pipeline {
    agent { 
        dockerfile {
            filename 'Dockerfile'
            dir 'ci'
        }
    }
    stages {
        stage('checkout gerrit patchset') {
            steps{
                echo "gerrit branch: ${GERRIT_BRANCH}, gerrit refspec: ${GERRIT_REFSPEC}"
                checkout([$class: 'GitSCM', branches: [[name: "$GERRIT_PATCHSET_REVISION"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'sm_gerrit', refspec: "${GERRIT_REFSPEC}", url: 'https://gerrit.rdk.tvlab.cloud/a/tdc/streamfs']]])
            }
        }
        stage('build') {        	
            steps {
                    sh label: '', script: '''#!/bin/bash
                        echo \'############################################\'
                        echo \'Building StreamFS\'
                        echo \'############################################\'

                        mkdir build
                        cd build
                        cmake ../
                        make
                    '''
                }
            }
        stage('Test') {        	
           	steps {
           		sh label: '', script: '''#!/bin/bash
            		
           		echo '************************************'
				echo "Running Unit tests"
    			echo '************************************'

                cd build/tests
                ./unit_tests

            	'''
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}